using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Primitively;

/// <inheritdoc />
[Generator]
public class SourceGeneration : IIncrementalGenerator
{
    private const string EmbedAbstractions = "EMBED_PRIMITIVELY_ABSTRACTIONS";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Register the abstractions sources
        context.RegisterPostInitializationOutput(i =>
        {
            foreach (var resource in EmbeddedResources.Abstractions.GetEmbeddedResources())
            {
                var sb = new StringBuilder(EmbeddedResources.AutoGeneratedHeader);
                sb.AppendLine();
                sb.AppendLine($"#if {EmbedAbstractions}");
                sb.AppendLine();
                sb.Append(resource.Value);
                sb.AppendLine();
                sb.AppendLine("#endif");

                i.AddSource($"{resource.Key}.g.cs", sb.ToString());
            }
        });
    }
}
