//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Primitively source generator
//
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 // publicly visible type or member must be documented
#pragma warning disable CS0162 // Unreachable code detected
