namespace Primitively.IntegrationTests.GuidTests.X;

public class TypeConverterTests : PrimitiveTypeConverterTests<SixtyEightHexadecimalsWithHyphensAndBraces.TypeConverter, SixtyEightHexadecimalsWithHyphensAndBraces>
{
}
