namespace Primitively.IntegrationTests.GuidTests.P;

public class TypeConverterTests : PrimitiveTypeConverterTests<ThirtyEightDigitsWithHyphensAndParentheses.TypeConverter, ThirtyEightDigitsWithHyphensAndParentheses>
{
}
