namespace Primitively;

/// <summary>
/// Defines a contract for a Primitively type that encapsulates a <see cref="Guid"/> value.
/// </summary>
/// <remarks>
/// Implementations of this interface are source generated by Primitively and inherit from the <see cref="IPrimitive{T}"/> interface.
/// </remarks>
public interface IGuid : IPrimitive<Guid>
{
}
