namespace Primitively;

/// <summary>
/// Defines a contract for a Primitively type that encapsulates an <see cref="int"/> value.
/// </summary>
/// <remarks>
/// Implementations of this interface are source generated by Primitively and inherit from both <see cref="IPrimitive{T}"/> and <see cref="IInteger"/> interfaces.
/// </remarks>
public interface IInt : IPrimitive<int>, IInteger
{
}
