namespace Primitively;

/// <summary>
/// Defines a contract for a Primitively type that encapsulates an integer value.
/// </summary>
/// <remarks>
/// Implementations of this interface are source generated by Primitively and inherit from the <see cref="IPrimitive"/> interface.
/// </remarks>
public interface IInteger : IPrimitive
{
}
