namespace Primitively;

/// <summary>
/// Defines a contract for a Primitively type that encapsulates a <see cref="ulong"/> value.
/// </summary>
/// <remarks>
/// Implementations of this interface are source generated by Primitively and inherit from both <see cref="IPrimitive{T}"/> and <see cref="INumeric"/> interfaces.
/// </remarks>
public interface IULong : IPrimitive<ulong>, INumeric
{
}
